Improves error messages for errors originating outside Tripy
- Adds the `ir.Location` attribute for all MLIR operations we generate.

    When we compile, we intercept `stderr` and parse out the location field from
    any error messages. From there, we can trace it back through the FlatIR to user code.

    Here's an example of such an error:

    ```
    tripy.common.exception.TripyException:

    --> /tripy/tmp.py:66 in test_dtype_mismatch()
        |
     66 |     print(c)
        |

    InternalError: InternalError: failed to run compilation pipeline
        error: 'stablehlo.add' op requires compatible types for all operands and results

        Note: This originated from the following expression:

        --> /tripy/tmp.py:65 in test_dtype_mismatch()
            |
         65 |     c = a + b
            |         ^^^^^

        Input 0:

        --> /tripy/tripy/frontend/ops/tensor_initializers.py:36 in ones()
            |
         36 |     return full(shape, 1, dtype)
            |            ^^^^^^^^^^^^^^^^^^^^^

        --> /tripy/tmp.py:63 in test_dtype_mismatch()
            |
         63 |     a = tp.ones((2, 4), dtype=tp.float16)
            |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ --- required from here

        Input 1:

        --> /tripy/tripy/frontend/ops/tensor_initializers.py:36 in ones()
            |
         36 |     return full(shape, 1, dtype)
            |            ^^^^^^^^^^^^^^^^^^^^^

        --> /tripy/tmp.py:64 in test_dtype_mismatch()
            |
         64 |     b = tp.ones((2, 4), dtype=tp.float32)
            |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ --- required from here
    ```

- Adds a `reason_details` field to `FlatIRTensor.build`. Any time we create an
    intermediate tensor in the FlatIR, we need to explain why we are doing so, otherwise
    the user will have no idea where the tensor came from, and will not understand any
    errors that it causes. With this field, we can generate nicer error messages like:

    ```
    tripy.common.exception.TripyException:

    --> /tripy/tmp.py:60 in test_broadcast_error()
        |
     60 |     print(c)
        |

    InternalError: InternalError: failed to run compilation pipeline
        error: size of operand dimension 1 (3) is not equal to 1 or size of result dimension 1 (4)

        This error occured while trying to compile the following FlatIR expression:
            |
            | t_inter5: [shape=(2, 4,), dtype=(float32), loc=(gpu:0)] = BroadcastOp(t5, broadcast_dim=[0, 1])
            |
        This operation was introduced by Tripy in order to broadcast the left operand of '+', which was:

        --> /tripy/tripy/frontend/ops/tensor_initializers.py:36 in ones()
            |
         36 |     return full(shape, 1, dtype)
            |            ^^^^^^^^^^^^^^^^^^^^^

        --> /tripy/tmp.py:57 in test_broadcast_error()
            |
         57 |     a = tp.ones((2, 3), dtype=tp.float32)
            |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ --- required from here

        to a shape of: (2, 4) in order to be compatible with the other input(s).

        Note: This originated from the following expression:

        --> /tripy/tmp.py:59 in test_broadcast_error()
            |
         59 |     c = a + b
            |         ^^^^^

        Input 0:

        --> /tripy/tripy/frontend/ops/tensor_initializers.py:36 in ones()
            |
         36 |     return full(shape, 1, dtype)
            |            ^^^^^^^^^^^^^^^^^^^^^

        --> /tripy/tmp.py:57 in test_broadcast_error()
            |
         57 |     a = tp.ones((2, 3), dtype=tp.float32)
            |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ --- required from here

        Input 1:

        --> /tripy/tripy/frontend/ops/tensor_initializers.py:36 in ones()
            |
         36 |     return full(shape, 1, dtype)
            |            ^^^^^^^^^^^^^^^^^^^^^

        --> /tripy/tmp.py:58 in test_broadcast_error()
            |
         58 |     b = tp.ones((2, 4), dtype=tp.float32)
            |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ --- required from here
    ```

- Adds function names in stack trace prints to make it easier to trace
    the flow of execution (see examples above).